//! The explicit field isomorphism between the two GF(2^128) representations:
//! GHASH [`super::gf2_128::F128`] and the tower [`super::tower_f128::F128T`].
//!
//! Constructed once offline (scratchpad/iso.py): X below is a root of
//! x^64+x^4+x^3+x+1 inside GHASH's 2^64-subfield (found by Cantor-Zassenhaus
//! trace splitting), Y solves y^2 + y = X^61 (an F_2-linear solve), and
//! psi(x^i y^j) = X^i Y^j extends F_2-linearly to a field isomorphism; phi is
//! its matrix inverse. The tests re-verify multiplicativity at runtime.
//!
//! Used at the flock boundary of the 64-bit transition: flock's zerocheck
//! (phi_8, GF(2^8) NTT, univariate skip) stays entirely in GHASH; its output
//! claim (point and value) maps through [`ghash_to_tower`] before the
//! ring-switch reduction and the K-committed PCS, which live in the tower.
//! Mapping a claim is sound because the packed polynomial has F_2 (bit)
//! coefficients: for a bit-valued multilinear w, w-hat(phi(r)) = phi(w-hat(r)).

use super::gf2_128::F128;
use super::tower_f128::F128T;

/// phi(a): GHASH to tower.
pub fn ghash_to_tower(a: F128) -> F128T {
    let mut c0 = 0u64;
    let mut c1 = 0u64;
    for (k, &(t0, t1)) in GHASH_TO_TOWER.iter().enumerate() {
        let bit = if k < 64 { (a.lo >> k) & 1 } else { (a.hi >> (k - 64)) & 1 };
        let m = 0u64.wrapping_sub(bit);
        c0 ^= t0 & m;
        c1 ^= t1 & m;
    }
    F128T::new(c0, c1)
}

/// psi(a): tower to GHASH.
pub fn tower_to_ghash(a: F128T) -> F128 {
    let mut lo = 0u64;
    let mut hi = 0u64;
    for (k, &(g0, g1)) in TOWER_TO_GHASH.iter().enumerate() {
        let bit = if k < 64 { (a.c0 >> k) & 1 } else { (a.c1 >> (k - 64)) & 1 };
        let m = 0u64.wrapping_sub(bit);
        lo ^= g0 & m;
        hi ^= g1 & m;
    }
    F128::new(lo, hi)
}

/// phi: GHASH basis x^k -> tower (c0, c1). Generated by scratchpad/iso.py.
pub(crate) const GHASH_TO_TOWER: [(u64, u64); 128] = [
    (0x0000000000000001, 0x0000000000000000),
    (0xd79b4f292e39763e, 0xa540d24f89d2ce83),
    (0x837e39f4992a9896, 0xdbd7c2067673eeab),
    (0x62c57f9bc40af8d7, 0xa2b7a95ae6bed73a),
    (0xf993bb9d14a40226, 0xf148ff8a48708bb0),
    (0xba727d6abd565b34, 0x2c5b4b73cb52adf3),
    (0x7405827b6e8e240b, 0xf0fde72bf79f517f),
    (0x9f21eefa37d930a0, 0x714e34acbec85143),
    (0x17973ca6f1f15bd3, 0x2eb5478e808907da),
    (0xe876ac9eb302352f, 0xfa83cf9470213db5),
    (0xcfc86acb23c84d94, 0x76697965e5cf24e4),
    (0xa9da0a24084395a3, 0x80097bb6372c4d2b),
    (0x80f600c0c8bbbe4a, 0xa4248272198cff46),
    (0xe93e75348865e39b, 0x8a844906afa40108),
    (0x5b5cda0179acfe98, 0x049dceb8cf6f76c7),
    (0x29a628449473da07, 0x2be4c429ad25ccaa),
    (0x64da792dd0e76a81, 0x5635edd763a92cb0),
    (0x6d281ffd8ed39394, 0x0e15078011fcea6a),
    (0x4b6e02afdc3747e8, 0x295588e2e4a13fc0),
    (0xfa8f409373984bf7, 0xfef1e52c0afeba64),
    (0xe1c9ac0e0f30be46, 0x2599151f8b95135b),
    (0xfa187316cee7cb52, 0x87f459179dba3ff4),
    (0x6f897f23965d9b2c, 0x8a2a0515a3c1659d),
    (0xe2fcdbe96a25b60d, 0x53f34eac5ca37810),
    (0x3cb66e7fd06bb73c, 0x59e25bcd2a71ae5f),
    (0x6ece460e19c54d83, 0x0202dfc6681e5cb9),
    (0xd864e1ad24743672, 0x05ff0b436db40397),
    (0xc375e3b2d1b0f7ac, 0x087a2c3a82b4acc2),
    (0xe914201e5af6a095, 0xa3c79072c41dc3aa),
    (0x64714adafc97763c, 0x535bb353a52e34d8),
    (0x052ca17f1a659f3a, 0x5dc2334c43c05d3e),
    (0x4f0f88ce20980c37, 0x7945216a4d264988),
    (0x326e0b55caa304ad, 0x7db265da3e785fa3),
    (0xb7347a15749a4dd4, 0x5066c4495896eaf3),
    (0x9d22743e08809524, 0x0c3a9ff6ab0ba888),
    (0xbe94ac19e6387fad, 0x8c5917c65497c81f),
    (0xd92c30a5d3edb330, 0x7d95dd59872498d8),
    (0xb40cd7783ff90832, 0x04143f6716cfd57c),
    (0x14f0d40ef8acf102, 0x00bea490b1defe42),
    (0x358d4d492fc20ca7, 0xdfd95939caaa80ef),
    (0x31a1ef17f58a1a0b, 0x5bd13994375c1a84),
    (0x1d62aa205950799c, 0xd01f3a989f5aa91c),
    (0xd1690a213fbc4414, 0x012287eb511c9f01),
    (0xeaa108656952e519, 0x04d8b1dc91e2b87b),
    (0x18bced2694f8339c, 0x0552755a2b74b75b),
    (0x6235838c607142be, 0x7547594b95b8f7f2),
    (0xb20f47158afeb0a0, 0x744086e744b554cd),
    (0x10d59308e9a51728, 0x523661012863896f),
    (0x88eeabf477eca372, 0x533012d9d3c8cc51),
    (0xc4fe3533356a1577, 0x23b44ef4c18847d8),
    (0xce762633dcdd739f, 0x2858027efaa0693a),
    (0xaf915bb369a43913, 0x2c409695de92bf15),
    (0x7c2c8db01fba4f4c, 0x2bfa8a2e0d67e2c4),
    (0x309293040e445ed8, 0xa900a9948eba0da8),
    (0x67b207106644d2d5, 0x8d8b09785e404350),
    (0x6849e17ca7db378f, 0x5596acf4428c43d5),
    (0xf7ff3f34a304de3e, 0xf8c0e121160906ff),
    (0xb5772e6ec4ac7bfd, 0xf74088b70ec086a8),
    (0x67862fea11d992cb, 0xdecf53cb64cdf443),
    (0xca4bb1b4f3b2ffcd, 0xab7e25e848018260),
    (0xbc865f0b8b68777c, 0x78d240d8cc4f6465),
    (0x75551167fef31f46, 0x7ea9b7fbbe0a98a0),
    (0x628cf3febacce8e5, 0xa3176b7ef8b735f5),
    (0xa2680959815bf8af, 0x0f98d895cbd6a2b7),
    (0xe2103d34ca5fc748, 0x8a73445b99f2537f),
    (0x9ea6560675d42652, 0xdfa40109fe05ef9c),
    (0x1996ab3af408a824, 0x7483399e4bebc791),
    (0x0e178aa80cdffe3e, 0xf7d74df361292d29),
    (0x9f1e5d821fe132ca, 0x866ae3df30808d38),
    (0xc45f7ae8ef4a91d6, 0xad885e533b3d9e7d),
    (0x326f3338f4a52903, 0xacc3d99c9500e1bd),
    (0x0c4f24f8674dcac7, 0xae126d87e8ab7972),
    (0xbca6e19d1f29546a, 0x00f1bd785a55f91b),
    (0xf5d4d46a8f50f186, 0x21768ac3637d897e),
    (0xb34118d34b910c09, 0x014895ca422f912e),
    (0x5f7a26d5424c39b6, 0x24075e8820cf623b),
    (0x0af0a219c753cc1c, 0x8a0fc29df1c59608),
    (0xd33bb256de42f0b2, 0x2f24278f67e5e221),
    (0x4ebcbef05ae1d701, 0x7888533ddbb64b9e),
    (0x37f8190565c59ed0, 0xa8418d932d6ceb66),
    (0x8aa996136ada8039, 0x514af496e133356d),
    (0x3e41741815b8da79, 0x8bb5b425cb1fb9bf),
    (0x277ec0298a06f181, 0x54aa1a866bd7b9a2),
    (0x902cd1a5d5c4b891, 0x5a6ad9e5ff6416ec),
    (0x7f55f2b1962977fc, 0x2234da75012a356c),
    (0x3066325f13197484, 0x86f67fd5cf05f110),
    (0x4e5d84dda08ca59e, 0x816c7385e4b8f26a),
    (0x478a73feba27bde3, 0x532f98edbebeb77c),
    (0x59395b4a9dd19065, 0x0bdf7cfb077f79d2),
    (0xfa7cdbb0b8f4464c, 0xa01209638dcf7431),
    (0x4fd7972a28ba6197, 0x0f77e90df19fc74b),
    (0xb2b87150710f1787, 0xd2daec92ad609568),
    (0x2189a745240c137c, 0xad43ea2fa1969b01),
    (0xb6e50809cf517eaa, 0xdc95ef2a379f6a60),
    (0xe06a4c64463816d5, 0x5e58c5b138b428b1),
    (0x4fa68fd564ac5f1a, 0xfafb98dca5f87495),
    (0x29a0680aa58e6f2f, 0xf4e44e809676f999),
    (0xd2b77a3223427f72, 0xf3ea594d7e675b8f),
    (0x48d6e2a9d0b435d3, 0x78e1ede34e1cafe0),
    (0x8d0dc9740ee52e81, 0x88f33e7acb41c401),
    (0x19c87e4d6cf5f33b, 0x7f0bd38028598ab0),
    (0x94354d18488c88c5, 0x0d6a21d0742d813d),
    (0x85656e08377f6d92, 0x744be2053f1fb774),
    (0x03a15793883f0cee, 0x7554a330b40881be),
    (0xabc43b8d45909c47, 0xd5c22b7f25507618),
    (0xbe3b5c15a691da7f, 0x8ce29d31126cc80b),
    (0x9ddd8e3860afce5a, 0xd51e8a8555193d4f),
    (0x46e25e65fe2ddb0c, 0x085e432f2b49328f),
    (0x1fec71cb461c9a90, 0xac73ad6e2dbfa12f),
    (0x68c36df17643a4eb, 0x78ed78e00b8608f8),
    (0x247d7d13a27dd784, 0x7553351576e4af6f),
    (0x26d5c1dcd67501c7, 0x289ea970acb27df8),
    (0x421670513d5c4aaa, 0x01a6e08c381e721e),
    (0x378fe8357605d9c4, 0x0597ebfa0c6eb271),
    (0xe0286291f88a7cd1, 0x0d25c00d0da5e58c),
    (0x09349358704233c3, 0x0e1ff440d27fed67),
    (0xa4cbb7cad4642c01, 0xf0164eaffcc0cde6),
    (0x61127e9f777d992d, 0xd0f6d791df9ab1f7),
    (0x995e33a8cfe0e83a, 0x75ed803a5b501d2f),
    (0x34ca381d5f55d054, 0xf17a15e59e642b7f),
    (0x61a4aea51d056a77, 0x232ef671482ef38f),
    (0xd5f25c30c48f46ac, 0xb61ec0f46b94e84a),
    (0x16b05537edcf8864, 0x0a9d5533ef008b43),
    (0x40f3c1c36cfc58b3, 0xf0f2a1d1add6afda),
    (0x6019c8f48c97c141, 0xf26ebfa7bf4f2ab5),
    (0x2b31a14e04a55d6e, 0x2115cf535d88b1e3),
    (0xbb2847567a58766a, 0xae8919a653853f7c),
    (0x7c8e3024a6c65a82, 0x1bdcf529a43141a8),
];

/// psi: tower basis (x^i y^j), index i + 64 j -> GHASH (lo, hi). Generated by scratchpad/iso.py.
pub(crate) const TOWER_TO_GHASH: [(u64, u64); 128] = [
    (0x0000000000000001, 0x0000000000000000),
    (0x528b4c52d01d3c6e, 0xe67564b88aedafb7),
    (0xb2f78445f25850ee, 0xb762a3b874036be5),
    (0x8e41081421542464, 0xebff7f6ad5b6dca9),
    (0xb67413d15e70e1ca, 0x14e53b2a9ea86adb),
    (0xed0a10a602e8b5ae, 0x451cf8c8b8cb6ba1),
    (0x3bd540551a83fc06, 0xcf241020c0614ee5),
    (0x7b154d5bbee98396, 0x3c707bc774771a67),
    (0x7ddbe8ca1bf4441f, 0xca4fb1e5b95c6efc),
    (0x564a917716b32a07, 0xfb980e4f2ffa2f34),
    (0x7aedc7110a699ceb, 0x2ca6aedf0be9d5f7),
    (0xb01dbee220c03be6, 0x616c79c02beb59e3),
    (0xb14e2c8a0ed7b0bc, 0x9e6c456197020d38),
    (0x5798a72fa74b6536, 0x1d490ae55f5c0c6a),
    (0xa62eb5aae4d326f1, 0xa7ffea1bd823aba4),
    (0x7558d722866a304a, 0x2511aa29c891ebce),
    (0x7b0a8baa579717ba, 0x86850a4d0fecf490),
    (0x65eeec5c76c69068, 0x925449f05fd339cc),
    (0x36144ddb336d8634, 0x196e76846aa54e3c),
    (0xba0624dcb770b6aa, 0xc2c1b5454d53d58b),
    (0x2334992f7e8c74a0, 0x20d7821ea7901d2a),
    (0xff200e5f00dd2687, 0x3549069af1dd3464),
    (0x3b70df53d329ffb9, 0x298d44eb8f3ae406),
    (0xf3627660f5a163d6, 0x82336ae8c54a6b57),
    (0x4dbf53096c35eff7, 0x29a755ec7cad2ce2),
    (0x332460e205935bfa, 0x25e57577f460f8e4),
    (0x9836cef53dab4ac8, 0xbf2a100767e2a0aa),
    (0x540f53caee38e135, 0x61103e2f05e2c10d),
    (0x42d24fbdfb6c9018, 0x92d40454cacde036),
    (0x50bb509ce5122d86, 0xdfdb8009a0fe133d),
    (0xd1f553e88a728ae6, 0x01e696e4aecb396a),
    (0xedce64011f0673dd, 0x8bbdbcc0e1a1f092),
    (0x3a15c48e22441223, 0xdf08c8b363911d73),
    (0xbc1337c6ae6fa718, 0x352d5f821d7aebd6),
    (0xc916658dfb6e9d97, 0x5105ab2c053c3a58),
    (0x5f7875d40a090bdb, 0x2d5d12549f4f3acd),
    (0x4afac0ae1bbab7a0, 0xa35946b6f11c993f),
    (0xd46678b94ae2ef20, 0xe60ac29cf02bd653),
    (0x1c2ae0b27ac2b340, 0xf771b0b057ef29af),
    (0x7d87f907eca39f66, 0xded4bed15a1066fe),
    (0xc39e0750bb257ad2, 0x182c38da835da8da),
    (0xe596034ce80cfd06, 0xcb81b24edfc4fc57),
    (0x2bae4f64976e256b, 0xc6aa55470a1975a2),
    (0xf19753c73b58b6e8, 0x64067aef99264e5f),
    (0xba2cbcb6f1254e23, 0x3823fc3f290e9e7f),
    (0xb5e8dd4e68544fa8, 0x6d9ed64e4d14e197),
    (0xedee17d75b56bc98, 0x971b8d955ae399e9),
    (0x51b32e999a1fb891, 0xabceb44d046512ca),
    (0xd6c3f02461cefa07, 0x2d3593b6eed985fb),
    (0xa6a3d5688737ad08, 0x0d149e70dd16ed86),
    (0x236b2d2e1baef03a, 0x11d9a0edf7fdb5c4),
    (0xe162fa261242dc47, 0xbea9e983e36cc4ad),
    (0x6391ea7acc67bef5, 0x31693ac8d7545ff0),
    (0x7bf7ab2236d54aab, 0x69f67e9110ef1408),
    (0x5c88ab75e4862910, 0x7d978757a1ab676f),
    (0xa9509c5e2fa6f235, 0x64d92d7d281205b2),
    (0xc6b08d4ced02804b, 0x55316e74182dba08),
    (0xa8d97c6949cf5eea, 0xab773ed952ef8707),
    (0x883a01a881c8e67c, 0x0d02513fd1006034),
    (0x5254050e7481148a, 0x1d5a06ec7f0702f5),
    (0xb7c1865dfa091bc8, 0x51adf35c5c42f013),
    (0x0b57dc45262d2e09, 0x5036f5c1ba00725e),
    (0xadf1dcb83e24042a, 0xb72922406689b02a),
    (0xb531e8fb280fe6f1, 0x0d4c4e2168f5aec2),
    (0x962361b9a1691f68, 0xce81261d6ab3aa3c),
    (0x0bfe4df9fe8bb2ae, 0xda99c480026deb7c),
    (0x653055bd41bfc780, 0x69c7159882c98c33),
    (0xe5b5811c380dc255, 0xa3da9082dc03fea4),
    (0x72a2294b86cf66b7, 0x10e358eb474ff84e),
    (0x6440c7e2e7d73d67, 0x4d9a84c1006f496b),
    (0xd1012dc6f5027103, 0x6c47936877d79fbc),
    (0x202542b44a08280e, 0x458741ccc7418d80),
    (0x11b9c53442d9f34b, 0x4404ed7071c37834),
    (0x472ce39f05285aa6, 0x58605b726bf6f1ea),
    (0x3d2720c8df75cd5d, 0x839ff1327c8ad5aa),
    (0x2ef2d1275e75c39d, 0x61a0da2293a53174),
    (0x99015b0c0d64e973, 0x201977bf8f6e2723),
    (0x059d114477dec73f, 0x8ad53faad6c210e6),
    (0xa77fd9d4a44273d2, 0x681f0a9c984a71a4),
    (0x0c89c54c0985e29d, 0xdb2924e9b889772d),
    (0xdd07d62519a11bef, 0x1dccab38ac3ab2f6),
    (0x80a0687ac85090b7, 0xfff44757dac01a8a),
    (0xff0ed37d5dc0c560, 0x512b15f09b6d022c),
    (0x797568dc098549c4, 0xdfb11edceaf1e67f),
    (0xf299a7b7eb19d156, 0x9b56795218b09430),
    (0xb0f06fcb11098a4a, 0xe73cea0b8815d47c),
    (0xc11472285f3d5908, 0xfabde6c2b8bfc083),
    (0x6f9c1eb718a158ae, 0x417dcdc6cae5fe2e),
    (0x11370e7b4996a5fc, 0xb7dc2467d133fd18),
    (0xa6cf00b72e9de567, 0x74e6f3a08c205cb8),
    (0xbe2b6c55fb5bb6f4, 0xdfa4aa9c1dfad0b2),
    (0xb0662dbdea95f996, 0x5cce6ea3d6eb4f4f),
    (0x16a3817f738c6a29, 0xbf9177aa0a9b3477),
    (0x600a0c6f05cd105a, 0x9b01bd2ab871dfb7),
    (0x35338b0566f4348a, 0xcb9f957ee1ac593d),
    (0xab55f2b43f9feadf, 0x15efebe0ea81a45e),
    (0x65409e57f7307a3a, 0x8b286f5c6ee46482),
    (0xcee638707a36671a, 0x20475135cddca381),
    (0xa8f375c120430308, 0x5d5635b8c6461e42),
    (0x8da3c48d1e932e0f, 0x1105cc546b9fd2de),
    (0x85e8d2234f9648c5, 0x552dd3035ff5cafa),
    (0x3ffad59949b59228, 0x018979b92fc5a74f),
    (0xc91760737c810910, 0x402e0b7d03774685),
    (0x939c8b0fcce53724, 0xfe38fe26ef2a6664),
    (0x36ef3afab889d99e, 0x098963fb548d59f9),
    (0x31385d30a556e0a1, 0x297b84fd0d0718d3),
    (0x9c2c583601e19317, 0xf765cb5c1a52eab3),
    (0xcb6fc0fbe850e2ce, 0x2543b2dc9190069d),
    (0xb8fe6f7d9120ae2f, 0x2da041119079cf73),
    (0xd19ac9e5504599a9, 0x60dd8f339a4f2800),
    (0x793895f3f4e051af, 0xaf8b4af99d78a03e),
    (0x7f59f70a4ab8cb58, 0xf3c30edbc2a966b9),
    (0x0e35e9ddb944c2a2, 0x97fad4a407df378a),
    (0xf107288027e818fe, 0x7df68811faf7f67c),
    (0x7c261864388436ec, 0x51cae02c5aa40f6b),
    (0xce8d7077912c9bd9, 0xb69656ffde452cf0),
    (0xd0039f628c59acc3, 0x68e83eec734c3a62),
    (0x98c8f3cabe50a6a6, 0x6835eade3cf92051),
    (0xa05bfc55ce1fce02, 0xc213f73febf4fa92),
    (0x358b6537eae43717, 0xe60e08e5e275fc8c),
    (0x96457e2fd788776c, 0x7dbca92499f201fe),
    (0xf048a9456a3c7488, 0x242f6dfcb9e45081),
    (0x1bd5df5ab4e5b9f6, 0xceebb79c605e3e1f),
    (0xf2e1ba579cc0b6b4, 0x7d5951dfa3654b9e),
    (0xcd26fbcb9a89091e, 0xd98429488bcd9056),
    (0x0f7126f5295cfde4, 0xc7c69a5353fa3085),
    (0x95a701009b616614, 0x95bde3d8861b82ee),
    (0x27595d49be1889d3, 0x7cb0b451bcfd5911),
];

#[cfg(test)]
mod tests {
    use super::*;

    fn splitmix64(state: &mut u64) -> u64 {
        *state = state.wrapping_add(0x9E37_79B9_7F4A_7C15);
        let mut z = *state;
        z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
        z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
        z ^ (z >> 31)
    }

    #[test]
    fn is_a_field_isomorphism() {
        assert_eq!(ghash_to_tower(F128::ONE), F128T::ONE);
        assert_eq!(tower_to_ghash(F128T::ONE), F128::ONE);
        assert_eq!(ghash_to_tower(F128::ZERO), F128T::ZERO);
        let mut s = 1u64;
        for _ in 0..2_000 {
            let a = F128::new(splitmix64(&mut s), splitmix64(&mut s));
            let b = F128::new(splitmix64(&mut s), splitmix64(&mut s));
            // multiplicative, additive, and a two-sided roundtrip
            assert_eq!(ghash_to_tower(a * b), ghash_to_tower(a) * ghash_to_tower(b));
            assert_eq!(ghash_to_tower(a + b), ghash_to_tower(a) + ghash_to_tower(b));
            assert_eq!(tower_to_ghash(ghash_to_tower(a)), a);
        }
        let mut s = 2u64;
        for _ in 0..2_000 {
            let t = F128T::new(splitmix64(&mut s), splitmix64(&mut s));
            assert_eq!(ghash_to_tower(tower_to_ghash(t)), t);
        }
    }
}
