[package]
name = "lean_vm"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
parallel.workspace = true
primitives.workspace = true
fiat_shamir.workspace = true
pcs.workspace = true
flock.workspace = true
tracing.workspace = true
zk_alloc.workspace = true

[dev-dependencies]
bincode.workspace = true
