name = "xmss-security"
version = "0.1.0"
defaultTargets = ["XmssSecurity"]

[[require]]
name = "VCVio"
git = "https://github.com/Verified-zkEVM/VCVio.git"
rev = "cbd4144"

[[lean_lib]]
name = "XmssSecurity"
