//! The Python reference verifier's field must agree with the tower bit for bit.
//! Vectors generated by `python-verifier/verifier.py`'s `F128.__mul__`.
#[test]
fn python_field_agrees_with_the_tower() {
    use primitives::field::F128T;
    let cases: [((u64, u64), (u64, u64), (u64, u64)); 3] = [
        (
            (17485029721327973432, 7283207964119141687),
            (890727360438182992, 15149836622520594227),
            (15433476914860349600, 9230090634532843285),
        ),
        (
            (1736392818365009963, 10750541312280087032),
            (16781078052021535861, 3960482443532127989),
            (496324119507325985, 2617854374097667762),
        ),
        (
            (1585446675937841368, 7713914763314685786),
            (4439448776366754703, 10165027665383847897),
            (12743549532723501032, 6619211339398375321),
        ),
    ];
    for (a, b, want) in cases {
        let got = F128T { c0: a.0, c1: a.1 } * F128T { c0: b.0, c1: b.1 };
        assert_eq!((got.c0, got.c1), want, "tower and python disagree");
    }
}
