#!/usr/bin/env bash
# Regenerate doc/leanvm/drafts/: one tiny driver per section, so that pressing the
# LaTeX build key inside a section file compiles only that section.
#
# Run this after adding, renaming or renumbering a section.
#
# Each driver reuses the shared preamble, numbers its section as in main.tex,
# and resolves cross-references and citations against ../.build/main.aux, so
# build main.tex once first. Each file in body/ gets a "% !TeX root" comment
# pointing at its driver; that is what LaTeX Workshop follows.
set -euo pipefail
cd "$(dirname "$0")"

python3 - <<'PY'
import glob, os, re

os.makedirs('drafts', exist_ok=True)
made = []

for path in sorted(glob.glob('body/*.tex')):
    name = os.path.basename(path)
    prefix = name[:-4].split('-')[0]
    if prefix.isdigit():                      # 01..10 are sections
        appendix, counter = '', int(prefix) - 1
    else:                                     # a, b, ... are annexes
        appendix, counter = '\\appendix\n', ord(prefix) - ord('a')

    open('drafts/' + name, 'w').write(f"""% GENERATED by make-drafts.sh. Do not edit; edit the section itself.
\\documentclass[11pt]{{article}}

\\input{{../preamble/packages}}
\\input{{../preamble/macros}}
\\input{{../preamble/theorems}}

\\usepackage{{xr}}
\\externaldocument{{../.build/main}}

\\pagestyle{{empty}}

\\begin{{document}}
{appendix}\\setcounter{{section}}{{{counter}}}
\\input{{../{path[:-4]}}}

\\bibliographystyle{{alphaurl}}
\\bibliography{{refs}}
\\end{{document}}
""")

    src = re.sub(r'^% !TeX root = .*\n', '', open(path).read())
    open(path, 'w').write(f'% !TeX root = ../drafts/{name}\n' + src)
    made.append(name)

# BIBINPUTS, because bibtex refuses a "../refs.bib" argument outright.
open('drafts/latexmkrc', 'w').write(
    "$pdf_mode = 1;\n"
    "$aux_dir = $out_dir = '.build';\n"
    "$bibtex_use = 2;\n"
    "$ENV{'BIBINPUTS'} = '..:.:' . ($ENV{'BIBINPUTS'} // '');\n"
)
print('%d drivers regenerated' % len(made))
PY
