[alias]
testall = ["test", "--release", "--workspace"]
clippyall = ["clippy", "--release", "--workspace", "--all-targets", "--", "-D", "warnings"]
docall = ["doc", "--release", "--workspace", "--no-deps"]

[build]
rustdocflags = ["-D", "warnings"]

[target.'cfg(all())']
rustflags = ["-C", "target-cpu=native"]
